model: "spectralGP_model"
data_path: "datasets/df_merged_daily_phyto_2022-10-21.csv"

model_checkpoint_folder: "models/model_checkpoints"
model_checkpoint_file: "models/model_checkpoints/training_size_0.1_model_checkpoint.pt"

predictor: "Beam_temperature_corrected"
dependent: "synconc"

res_path: "results/"


split_folder: "datasets/split/"

take_log:
  desc: "option to take log of of dependent variable"
  value: true

wandb_mode: null
sweep: true


