model: "spectralGP_model"
data_path: "datasets/df_merged_daily_phyto_2022-10-21.csv"

model_checkpoint_folder: "models/model_checkpoints"
model_checkpoint_file: "models/model_checkpoints/training_size_0.1_model_checkpoint.pt"

predictor: "Beam_temperature_corrected"
dependent: "synconc"

res_path: "results/"


2D:
  desc: "whether to use 2 dimensions or not in x variable"
  val: true

split_folder: "datasets/split/"

take_log:
  desc: "option to take log of of dependent variable"
  value: true

wandb_mode: null
sweep: true

parameters:
  train_iter: 2000
  train_size: 0.1
  lr: 0.1
  better_lower_bound: 0.00001
  mixtures: 200
  num_dims: 2
  noise_value: 0.01
  noise_prior_loc: 0.0
  noise_prior_scale: 0.01


