model: "spectralGP_model"
data_path: "datasets/df_merged_daily_phyto_2022-10-21.csv"
res_path: "results/"
model_checkpoint_folder: "models/model_checkpoints"
model_checkpoint_file: "models/model_checkpoints/training_size_0.1_model_checkpoint.pt"
predictor: "daily_index"
dependent: "Guinardia_delicatula"

num_dims_predictor: 1
split_folder: "datasets/split/"
take_log: false
wandb_mode: null
