program: train/sweep.py
method: bayes
metric:
  name: mean_dir_acc
  goal: maximize

parameters:
  lr:
    min: 0.0001
    max: 0.1
  mixtures:
    min: 50
    max: 1000
  train_size:
    min: 1
    max: 8
  train_iter: 
    value: 2000
  better_lower_bound:
    value: 0.00001
  num_dims:
    value: 1
  noise_value:
    value: 0.01
  noise_prior_loc: 
    value: 0.0
  noise_prior_scale:
    value:  0.01
  num_dims_predictor:
    value: 2

  optimizer:
    values: ["adam", "sgd"]

early_terminate:
  type: hyperband
  min_iter: 2

command:
  - ${env}
  - ${interpreter}
  - ${program}


