program: train/sweep.py
method: bayes
metric:
  name: mean_dir_acc
  goal: maximize

parameters:
  lr:
    min: 0.0001
    max: 0.1
  mixtures:
    min: 50
    max: 1000
  train_size:
    min: 1
    max: 8
  train_iter: 
    value: 2000
  better_lower_bound:
    value: 0.00001
  num_dims:
    value: 1
  noise_value:
    value: 0.01
  noise_prior_loc: 
    value: 0.0
  noise_prior_scale:
    value:  0.01


  optimizer:
    values: ["adam", "sgd"]

early_terminate:
  type: hyperband
  min_iter: 2

command:
  - ${env}
  - ${interpreter}
  - ${program}

model: "spectralGP_model"
data_path: "datasets/df_merged_daily_phyto_2022-10-21.csv"
res_path: "results/"
model_checkpoint_folder: "models/model_checkpoints"
model_checkpoint_file: "models/model_checkpoints/training_size_0.1_model_checkpoint.pt"
predictor: "daily_index"
dependent: "synconc"

split_folder: "datasets/split/"

take_log:
  desc: "option to take log of of dependent variable"
  value: true

wandb_mode: null
sweep: true

