program: train/sweep.py
name: "Sweeping Syn"
method: bayes
metric:
  name: mean_dir_acc
  goal: maximize

parameters:
  lr:
    min: 0.0001
    max: 0.1
  mixtures:
    min: 50
    max: 2000
  train_size:
    min: 0.1
    max: 0.9
  train_iter: 
    value: 200
  better_lower_bound:
    value: 0.00001
  num_dims:
    value: 1
  noise_value:
    value: 0.01
  noise_prior_loc: 
    value: 0.0
  noise_prior_scale:
    value:  0.01
  optimizer:
    value: "adam"


command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--cfg"
  - "cfg/slurm_syn_config.yaml"

