method: grid
metric:
  name: mean_dir_acc
  goal: maximize
parameters:
  lr:
    min: 0.01
    max: 0.3
  mixtures:
    min: 300
    max: 1000
  train_size:
    min: 3
    max: 8

  optimizer:
    values: ["adam", "sgd"]

early_terminate:
  type: hyperband
  min_iter: 2
