program: train/sweep.py
name: "Sweeping Temperature, Syn"
method: bayes
metric:
  name: mean_dir_acc
  goal: maximize

parameters:
  lr:
    min: 0.0001
    max: 0.1
  mixtures:
    min: 50
    max: 1500
  train_size:
    min: 0.1
    max: 0.8
  train_iter:
    value: 200
  better_lower_bound:
    value: 0.00001
  num_dims:
    value: 2
  noise_value:
    value: 0.01
  noise_prior_loc:
    value: 0.0
  noise_prior_scale:
    value:  0.01
  optimizer:
    values: ["adam", "sgd"]

early_terminate:
  type: hyperband
  min_iter: 2

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--cfg"
  - "cfg/slurm_temp_config.yaml"

