wandb_version: 1

X_test_shape:
  desc: null
  value:
  - 2693
X_train_shape:
  desc: null
  value:
  - 2694
_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1662567170.545966
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 19
      - 23
      4: 3.10.4
      5: 0.13.1
      8:
      - 5
dependent:
  desc: null
  value: synconc
learning_rate:
  desc: null
  value: 0.1
num_mixtures:
  desc: null
  value: 4
predictor:
  desc: null
  value: daily_index
train_size:
  desc: null
  value: 0.5
y_test_shape:
  desc: null
  value:
  - 2693
y_train_shape:
  desc: null
  value:
  - 2694
