wandb_version: 1

X_test_shape:
  desc: null
  value:
  - 3591
X_train_shape:
  desc: null
  value:
  - 1796
_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1662567927.54438
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 19
      - 23
      4: 3.10.4
      5: 0.13.1
      8:
      - 5
dependent:
  desc: null
  value: synconc
learning_rate:
  desc: null
  value: 0.01
num_mixtures:
  desc: null
  value: 6
predictor:
  desc: null
  value: daily_index
sp_mixture_better_lower_bound:
  desc: null
  value: 0.001
train_size:
  desc: null
  value: 0.3333333333333333
y_test_shape:
  desc: null
  value:
  - 3591
y_train_shape:
  desc: null
  value:
  - 1796
