wandb_version: 1

X_test_shape:
  desc: null
  value:
  - 3342
X_train_shape:
  desc: null
  value:
  - 3343
_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1662565070.664935
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 3
      - 19
      - 23
      4: 3.10.4
      5: 0.13.1
      8:
      - 5
dependent:
  desc: null
  value: log_syn_interpolated
learning_rate:
  desc: null
  value: 0.1
num_mixtures:
  desc: null
  value: 4
predictor:
  desc: null
  value: lindex
train_size:
  desc: null
  value: 0.5
training_iter:
  desc: null
  value: 100
y_test_shape:
  desc: null
  value:
  - 3342
y_train_shape:
  desc: null
  value:
  - 3343
