model: "spectralGP_model"
data_path: "datasets/df_merged_daily_phyto_2022-10-21.csv"
#data_path: "/dos/MIT-WHOI/data/2022/dfmerged_daily_phyto_2022_Oct.csv"
res_path: "results/"
model_checkpoint_folder: "models/model_checkpoints"
model_checkpoint_file: "models/model_checkpoints/training_size_0.1_model_checkpoint.pt"
predictor: "daily_index"
dependent: "synconc"

split_folder: "datasets/split/"

#HYPERPARAMTERS
better_lower_bound: 0.00001
mixtures: 200
num_dims: 1
noise_value: 0.01

learning_rate: 0.1
training_iter: 2000
train_size: 0.2

noise_prior_loc: 0.0
noise_prior_scale: 0.01