
model: "spectralGP_model"
data_path: "/home/mira/PycharmProjects/gp_plankton_model/datasets/syn_dataset.pkl"
res_path: "/home/mira/PycharmProjects/gp_plankton_model/results/"
model_chkpoint_path: "home/mira/PycharmProjects/gp_plankton_model/model/model_chkpoints"